services:
    bitbag_sylius_invoicing_plugin.controller.action.download_order_invoice:
        class: BitBag\SyliusInvoicingPlugin\Controller\Action\DownloadOrderInvoice
        arguments:
            - "@bitbag_sylius_invoicing_plugin.repository.invoice"
            - "@bitbag_sylius_invoicing_plugin.resolver.invoice_file"

    bitbag_sylius_invoicing_plugin.controller.action.download_customer_invoice:
        class: BitBag\SyliusInvoicingPlugin\Controller\Action\DownloadCustomerInvoice
        arguments:
            - "@bitbag_sylius_invoicing_plugin.repository.invoice"
            - "@bitbag_sylius_invoicing_plugin.resolver.invoice_file"
            - "@sylius.context.customer"
            - "@sylius.repository.order"
