imports:
    - { resource: "@BitBagSyliusInvoicingPlugin/Resources/config/services.yml" }
    - { resource: "@BitBagSyliusInvoicingPlugin/Resources/config/resources.yml" }
    - { resource: "@BitBagSyliusInvoicingPlugin/Resources/config/grids.yml" }
    - { resource: "@BitBagSyliusInvoicingPlugin/Resources/config/state_machine.yml" }

parameters:
    wkhtmltopdf_binary_path: /usr/local/bin/wkhtmltopdf
    invoices_locale_code: "en"
    invoices_root_dir: "%kernel.root_dir%/../invoices"

sylius_mailer:
    emails:
        invoice:
            subject: bitbag_sylius_invoicing_plugin.emails.invoice.subject
            template: 'BitBagSyliusInvoicingPlugin:Email:invoice.html.twig'
            enabled: true

knp_snappy:
    pdf:
        enabled: true
        binary: "%wkhtmltopdf_binary_path%"
    process_timeout: 300
