winzou_state_machine:
    sylius_payment:
        callbacks:
            after:
                sylius_generate_invoice:
                    on:
                        - "complete"
                    do:
                        - "@bitbag_sylius_invoicing_plugin.state_resolver.invoice"
                        - "generateInvoice"
                    args:
                        - "object.getOrder()"
                    disabled: false
                    priority: 0
