BitBag\SyliusInvoicingPlugin\Entity\CompanyData:
    type: mappedSuperclass
    table: bitbag_invoicing_company_data
    id:
          id:
              type: integer
              id: true
              generator:
                  strategy: AUTO
    fields:
        name:
            column: name
            type: string
        street:
            column: street
            type: string
        city:
            column: city
            type: string
        postcode:
            column: postcode
            type: string
        vatNumber:
            column: vat_number
            type: string
        seller:
            column: seller
            type: string
        invoiceNumberTemplate:
            column: invoice_number_template
            type: string
            nullable: true
        validateCustomerVatNumber:
            column: validate_customer_vat_number
            type: boolean
            nullable: false
            options:
                default: 1
        generateInvoiceAfterPaymentSuccess:
            column: generate_invoice_after_payment_success
            type: boolean
            nullable: false
            options:
                default: 0

    oneToOne:
        channel:
            targetEntity: Sylius\Component\Core\Model\ChannelInterface
            cascade: ["ALL"]

